create schema if not exists stats;

create table
  stats.presets (
    preset_id bigint generated by default as identity (START WITH 100 INCREMENT BY 1) not null,
    user_id uuid not null default gen_random_uuid (),
    preset_name text not null default 'Preset'::text,
    last_updated timestamp without time zone null,
    left_background character varying null,
    left_bigtext character varying null,
    left_smalltext character varying null,
    right_background character varying null,
    right_bigtext character varying null,
    right_smalltext character varying null,
    mvpbanner_background character varying null,
    mvpbanner_text character varying null,
    mvp_agent character varying null,
    mvp_text character varying null,
    global_text character varying null,
    font character varying null,
    constraint presets_pkey primary key (preset_id),
    constraint presets_preset_id_key unique (preset_id),
    constraint presets_user_id_fkey foreign key (user_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;

  GRANT ALL PRIVILEGES ON SCHEMA stats TO postgres, anon, authenticated, service_role, dashboard_user;
  GRANT ALL privileges ON TABLE stats.presets TO postgres, anon, authenticated, service_role, dashboard_user;