name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production Deployment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        uses: oven-sh/setup-bun@v2

      - name: Add SSH host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh  # Set directory permissions
          chmod 644 ~/.ssh/known_hosts  # Set file permissions
          cat ~/.ssh/known_hosts  # Debugging output


      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ~/.ssh/known_hosts

          
      - name: Deploy to Production Server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
            ssh $DEPLOY_USER@$DEPLOY_HOST "\
            cd $DEPLOY_PATH && \
            git pull origin main && \
            bun install && \
            pkill -f 'bun ./build/index.js' || true && \
            bun run build && \
            nohup bun bun ./build/index.js > app.log 2>&1 &"