name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production Deployment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/known_hosts

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ~/.ssh/known_hosts

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Pull Latest Changes
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          set -e
          ssh $DEPLOY_USER@$DEPLOY_HOST "\
          cd $DEPLOY_PATH && \
          git pull origin main"

      - name: Build and Run Application
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST "\
          cd $DEPLOY_PATH && \
          export BUN_INSTALL=\"\$HOME/.bun\" && \
          export PATH=\"\$BUN_INSTALL/bin:\$PATH\" && \
          bun install && \
          bun run build"

      - name: Start Application
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST "\
          cd $DEPLOY_PATH && \
          export BUN_INSTALL=\"\$HOME/.bun\" && \
          export PATH=\"\$BUN_INSTALL/bin:\$PATH\" && \
          pkill -f 'bun ./build/index.js' || true && \
          nohup bun ./build/index.js > app.log 2>&1 &"