name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to Production Server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
            ssh $DEPLOY_USER@$DEPLOY_HOST "\
            cd $DEPLOY_PATH && \
            git pull origin main && \
            bun install && \
            pkill -f 'bun ./build/index.js' || true && \
            bun run build && \
            nohup bun bun ./build/index.js > app.log 2>&1 &"